### ISSUE TITLE
how do i figure out what my servers address is to connect

### ISSUE THREAD

**Issue by shinykody** [juharris/switch-remoteplay#24]
how do i figure out what my servers address is to connect

**Comment by juharris** [comment]
Hey, thanks for trying out the project. There are a few ways. If you're using a Raspberry Pi then you might be able to use http://raspberrypi.
What you want is the local/internal/private IP for the device. There are a few ways listed at https://opensource.com/article/18/5/how-find-ip-address-linux
I like `ip addr` where you might find something like `192.xxx.xxx.xxx` where each x is a digit.
You'll need to input that with the port on the client website. For example: `http://192.168.27.121:5000` since 5000 is the default port for the server.
