### ISSUE TITLE
joycontrol doesn't seem to be available on pip

### ISSUE THREAD

**Issue by lufinkey** [juharris/switch-remoteplay#36]
When I run the command `sudo -H pip3 install -e .` from the server directory, I get a 404 error for joycontrol:
```
404 Client Error: Not Found for url: https://pypi.org/simple/joycontrol/
```

**Comment by juharris** [comment]
Thanks for trying out the project!
I don't think it ever was. Idk why you would get that error. Maybe you're using an old version of pip?

I'm on a Raspberry Pi and I got:
```bash
$ sudo pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```
That does seem old (maybe cause of the Raspberry Pi?)...

Maybe you can install it with just `sudo pip3 install 'joycontrol @ git+https://github.com/mart1nro/joycontrol.git@721646a7ec10231490bcf788b3bdde10d8c2007f'` ?

Otherwise if you have issues install joycontrol, then I suggest that you see their repo: https://github.com/mart1nro/joycontrol

**Comment by lufinkey** [comment]
I was able to install it perfectly on a raspberry pi, but for some reason
it couldn't find the package when I was on Linux Mint

**Comment by juharris** [comment]
Weird. Sorry it sounds like something related to pip then. I'm going to close this issue for now but feel free to post here if you have more related issues/solutions to this problem.
